//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopper_Information
    {
        public string Display_Name { get; set; }
        public string User_Name { get; set; }
        public string password { get; set; }
        public string password2 { get; set; }
    }
}
