//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public int UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> UsersType { get; set; }
        public Nullable<int> MappingId { get; set; }
        public string PictureName { get; set; }
    
        public virtual MappingsTable MappingsTable { get; set; }
    }
}
